#!/bin/bash

if [ $# -eq 0 ]||[ ! -d $1 ] 
then
	echo "No Target Folder. e.g. check_style [target_folder]"
	exit;
fi

flist=`find $1 -name "*.c"`

for file in `echo $flist`
do
	echo $file
	perl ~/checkpatch_tizen.pl $file
	echo 
done

flist=`find $1 -name "*.cpp"`

for file in `echo $flist`
do
	echo $file
	perl ~/checkpatch_tizen.pl $file
	echo 
done

flist=`find $1 -name "*.h"`

for file in `echo $flist`
do
	echo $file
	perl ~/checkpatch_tizen.pl $file
	echo 
done
